### ISSUE TITLE
what happens when max_elements is exceeded ?

### ISSUE THREAD

**Issue by rvencu** [remram44/python-bloom-filter#3]
Not sure what happens but it would be nice to replace the oldest elements with new ones... 

or

is there any way to expand max_elements for an existing filter?

**Comment by remram44** [comment]
This is not how bloom filters work. You can read about the data structure here: https://en.wikipedia.org/wiki/Bloom_filter

As per the README of this repository, `max_elements` is how many elements you expect the filter to hold.

**Comment by rvencu** [comment]
Thanks
