### ISSUE TITLE
Multiprocessing and shared bloom filter

### ISSUE THREAD

**Issue by rvencu** [remram44/python-bloom-filter#4]
Hi, hopefully I start asking more intelligent questions... thank for answering anyway

My current task is to create a bloom filter from a file in the main process then pass it to several sub-processes. I was able to do that and had no problem with pickle/mmap thing.

Now I want to update the bloom file in some sub process. The question is, will all processes see the updated data or I need to search for more tricks to make that happen?

**Comment by remram44** [comment]
Interesting question! As you've realized, the array backends won't work, as they hold data in a process' privary memory.

For both the file-seek backend and the mmap backend, it is safe to add elements from one process and test membership from other processes. You can use locking if you have multiple processes writing.

Doing other write operations (like `clear()` or `&=`) might give strange results to concurrent readers, but won't cause a crash.

**Comment by rvencu** [comment]
Cool. What I am doing to be very very safe: 

- only one process writes (actually instead of writing I download updated files).
- I dropped the idea to pass the object from parent process. Instead I create and destroy objects in each sub process (except the one busy with updates). 
- I am also using some queues to signal such conditions that the update/download will take place at times when filters are not used. Also while updating the files, no process can start filtering...

Finally I am mapping the same files for read-only purposes from different processes in parallel. Seems to work and I feel better safe than sorry :)
