### ISSUE TITLE
Question: What is the best way to store and retrieve bloom filters?

### ISSUE THREAD

**Issue by bethylamine** [remram44/python-bloom-filter#7]
When transferring a bloom filter over a network, say, is there an easy way to write out a file or a string object that can then be subsequently loaded?

**Comment by bethylamine** [comment]
Answering my own question here: `pickle.dump`/`pickle.dumps` works fine, I was just getting confused when my tests failed but the keys were different between the creation and test of the bloom filter.

**Comment by remram44** [comment]
It depends on the backend you use. The array (default) will go through pickle, otherwise you can use the `filename` argument to use a raw file.
